version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bgituquizz
      POSTGRES_USER: bgituquizzuser
      POSTGRES_PASSWORD: bgituquizzpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: ./bgituQuizzAdmin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bgituQuizzAdmin:/app
    environment:
      - POSTGRES_DB=bgituquizz
      - POSTGRES_USER=bgituquizzuser
      - POSTGRES_PASSWORD=bgituquizzpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ML_GENERATE_CONTENT_URL=http://ml:8001/generate_content
      - ML_ANALYSE_SENTIMENT_URL=http://ml:8001/analyze_sentiment
    depends_on:
      - db
      - ml
    ports:
      - "8000:8000"

  ml:
    build: ./bgituQuizzML
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./bgituQuizzML:/app
    environment:
      - TRANSFORMERS_CACHE=/app/.cache
    ports:
      - "8001:8001"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  node:
    build: ./bgituQuizz
    command: npm start
    volumes:
      - ./bgituQuizz:/app
    environment:
      - ADMIN_API_URL=http://django:8000/api/active_game/
      - ML_API_URL=http://ml:8001
      - OPEN_ANSWER_THRESHOLD=0.7
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - django
      - ml
      - redis

  tg:
    build: ./bgituQuizzTG
    command: python main.py
    volumes:
      - ./bgituQuizzTG:/app
    environment:
      - ADMIN_API_URL=http://django:8000/api/active_game/
      - ML_API_URL=http://ml:8001
      - OPEN_ANSWER_THRESHOLD=0.7
      - TG_API_TOKEN=your_token
    depends_on:
      - django
      - ml

volumes:
  pgdata:
  redisdata: 